# Generated by Django 5.0.6 on 2024-06-11 16:43

import uuid

import django.db.models.deletion
import django.utils.timezone
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unique_identifier", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now=True)),
                ("content", models.TextField()),
                ("checksum", models.CharField(max_length=64)),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat",
                "verbose_name_plural": "Chats",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ChatSnipProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(default=uuid.uuid4, max_length=255, unique=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CodeFragment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "programming_language",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("source_code", models.TextField()),
                ("checksum", models.CharField(max_length=64)),
                ("selected", models.BooleanField(default=False)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_fragments",
                        to="chatsnipserver.chat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Code Fragment",
                "verbose_name_plural": "Code Fragments",
                "ordering": ["-timestamp"],
            },
        ),
    ]
