# Generated by Django 5.0.6 on 2024-06-12 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import chatsnipserver.models


class Migration(migrations.Migration):

    dependencies = [
        ("chatsnipserver", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="chats", to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name="ChatImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_url", models.URLField()),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(upload_to=chatsnipserver.models.chat_image_upload_to)),
                ("chat", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="images", to="chatsnipserver.chat")),
            ],
        ),
    ]
