# Generated by Django 5.0.6 on 2024-06-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatsnipserver", "0003_chatimage_blacklisted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatimage",
            name="source_url",
            field=models.CharField(max_length=500),
        ),
    ]
