# Generated by Django 5.0.6 on 2024-06-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatsnipserver", "0004_alter_chatimage_source_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatimage",
            name="checksum",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
