# Generated by Django 5.0.6 on 2024-06-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatsnipserver", "0005_chatimage_checksum"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chat",
            old_name="content",
            new_name="markdown",
        ),
        migrations.AddField(
            model_name="chat",
            name="json_data",
            field=models.JSONField(default=""),
            preserve_default=False,
        ),
    ]
