# Generated by Django 5.0.6 on 2024-06-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatsnipserver", "0006_rename_content_chat_markdown_chat_json_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="json_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="chat",
            name="markdown",
            field=models.TextField(blank=True, null=True),
        ),
    ]
