# Generated by Django 5.0.6 on 2024-06-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatsnipserver", "0008_chat_images_downloaded"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="chatbot",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="chat",
            name="llm_model",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
