# Generated by Django 5.0.6 on 2024-06-14 19:58

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatsnipserver", "0009_chat_chatbot_chat_llm_model"),
        ("taggit", "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True, help_text="A comma-separated list of tags.", through="taggit.TaggedItem", to="taggit.Tag", verbose_name="Tags"
            ),
        ),
    ]
